/* ─── Estado IDs mapeados al esquema de la BD ─── */
export const ESTADO_PLAZA       = { LIBRE:1, OCUPADA:2, RESERVADA:3, MANTENIMIENTO:4, ASIGNADA:5 };
export const ESTADO_TICKET      = { ACTIVO:1, CERRADO:2, VENCIDO:3, ANULADO:4, USADO:2 };
export const ESTADO_RESERVA     = { ACTIVA:1, CANCELADA:2, COMPLETADA:3, VENCIDA:4, EN_ESPERA:5, RECHAZADA:6 };
export const ESTADO_MANT        = { PENDIENTE:1, EN_PROGRESO:2, COMPLETADO:3, CANCELADO:4 };
export const ESTADO_USUARIO     = { ACTIVO:1, INACTIVO:2, SUSPENDIDO:3 };
export const ESTADO_ZONA        = { ACTIVA:1, INACTIVA:2, MANTENIMIENTO:3, CERRADA:4 };
export const ESTADO_ASIGNACION  = { ACTIVA:1, FINALIZADA:2, SUSPENDIDA:3 };
export const ESTADO_DISPOSITIVO = { OPERATIVO:6, FUERA_DE_SERVICIO:7, MANTENIMIENTO:3 };
export const ESTADO_VEHICULO    = { ACTIVO:1, INACTIVO:2 };
export const ESTADO_SUSCRIPCION = { ACTIVA:1, INACTIVA:2, CANCELADA:3, TRIAL:4 };

export const TIPO_EVENTO_ID    = { RESERVA_CREADA:4, RESERVA_CANCELADA:5, TICKET_EMITIDO:6, TICKET_CERRADO:7, MANT_INICIADO:9, MANT_COMPLETADO:10, CAMBIO_ESTADO:27, NUEVO_EMPLEADO:28, ACTUALIZAR_PERSONAL:29 };
export const ORIGEN_EVENTO     = { PANEL_WEB:1, APP_MOVIL:2, LPR:3, SISTEMA:4 };
export const TIPO_NOTIF        = { ALERTA:1, RECORDATORIO:2, CONFIRMACION:3, SISTEMA:4, ERROR:5, ADVERTENCIA:6 };
export const TIPO_REPORTE      = { OCUPACION:5, ACCESOS:2, INGRESOS:3, MANTENIMIENTOS:4, RESERVACIONES:6, VEHICULOS:7, AUDITORIA:8, OTRO:9 };
export const ROL               = { ADMIN:1, OPERADOR:2, TECNICO:3, SUPERVISOR:4, VISITANTE:5, MOVIL:6 };
